kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  image: kindest/node:v1.33.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      taints: []
- role: worker
  image: kindest/node:v1.33.0
